# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cServer.proto\"\x07\n\x05\x45MPTY\"\x1b\n\rget_genes_REQ\x12\n\n\x02id\x18\x01 \x01(\t\"\x1e\n\rget_genes_REP\x12\r\n\x05genes\x18\x01 \x01(\x0c\"@\n\x12return_results_REQ\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05genes\x18\x02 \x01(\x0c\x12\x0f\n\x07\x66itness\x18\x03 \x01(\x02\"%\n\x12return_results_REP\x12\x0f\n\x07success\x18\x04 \x01(\x08\x32\x64\n\x02\x45\x41\x12-\n\tget_genes\x12\x0e.get_genes_REQ\x1a\x0e.get_genes_REP\"\x00\x12/\n\x0ereturn_results\x12\x13.return_results_REQ\x1a\x06.EMPTY\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=16
  _EMPTY._serialized_end=23
  _GET_GENES_REQ._serialized_start=25
  _GET_GENES_REQ._serialized_end=52
  _GET_GENES_REP._serialized_start=54
  _GET_GENES_REP._serialized_end=84
  _RETURN_RESULTS_REQ._serialized_start=86
  _RETURN_RESULTS_REQ._serialized_end=150
  _RETURN_RESULTS_REP._serialized_start=152
  _RETURN_RESULTS_REP._serialized_end=189
  _EA._serialized_start=191
  _EA._serialized_end=291
# @@protoc_insertion_point(module_scope)
